### ISSUE TITLE
display: contents update

### ISSUE THREAD

**Issue by jhpratt** [Fyrd/caniuse#3584]
Chrome 59 supports with `#enable-experimental-web-platform-features`

I couldn't find anything on Chrome's issue, so I don't know if this is the first with support.

(visual test: https://codepen.io/rachelandrew/pen/rxvMWG?css-preprocessor=none)

**Comment by chharvey** [comment]
In addition, **Safari 10.1.2 for macOS** also supports `display: contents;`, with some bugs. (Parts of the box appear before and after its children, like pseudo-elements.)

See @jhpratt’s link for visual test.

**Comment by tobireif** [comment]
Some news:
https://twitter.com/regocas/status/971402883462811648
https://blogs.igalia.com/mrego/2018/01/11/display-contents-is-coming/

**Comment by tobireif** [comment]
Related: https://github.com/Fyrd/caniuse/issues/3353

**Comment by mestaritonttu** [comment]
The [entry](https://caniuse.com/#feat=css-display-contents) says:

> Safari support is buggy, see WebKit bug 188259 & WebKit bug 193567

Both of these WebKit bugs were closed as fixed in 2019.

Regarding the note

> Partial support refers to severe implementation bug that renders the content inaccessible

the bugs in question are still open and tracked in
https://bugs.chromium.org/p/chromium/issues/detail?id=835455
https://bugs.webkit.org/show_bug.cgi?id=185679

**Comment by Schweinepriester** [comment]
At the latest once #5856 is merged I believe this issue can be closed, right?

**Comment by mestaritonttu** [comment]
> > Partial support refers to severe implementation bug that renders the content inaccessible
> 
> the bugs in question are still open and tracked in
> https://bugs.chromium.org/p/chromium/issues/detail?id=835455

The Chromium bug is fixed since Mar 8, 2021

**Comment by Schweinepriester** [comment]
Yeah, and caniuse was updated accordingly in #5801, resulting in

![image](https://user-images.githubusercontent.com/2644614/115058669-cda87200-9ee5-11eb-82c9-c64f82ba8824.png)

(And #5856 addresses the still broken accessibility in WebKit)

**Comment by Fyrd** [comment]
Closing as per above
